### PR TITLE
CS50P: Cookie Jar: Add check for test function validity

### LINKED ISSUE #215: CS50P Week 8: pset "Cookie Jar" accepts and passes the test requirement when given the empty example for test_jar.py
check50 shows a passing grade when given the example test_jar.py file provided in the Hints section of the pset page:

```py
from jar import Jar


def test_init():
    ...


def test_str():
    jar = Jar()
    assert str(jar) == ""
    jar.deposit(1)
    assert str(jar) == "🍪"
    jar.deposit(11)
    assert str(jar) == "🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪"


def test_deposit():
    ...


def test_withdraw():
    ...

 ```
 
 This code should not pass without filling out the functions.

### PR DESCRIPTION
**Pull request by Makaze**
It is possible to pass the test file check with the example test, containing only ellipses (...) in the function body of all four test functions.

This PR adds a checker that makes sure the tests contain valid lines of code on top of passing.

Resolves #215.

### CODE REVIEW

**Comment by Makaze** [comment]
Am I missing anything?

**Comment by rongxin-liu** [comment]
> Am I missing anything?

Thank you for opening a PR. We will review it when the time comes.

**Comment by curiouskiwi** [comment]
Thanks @Makaze

**Comment by Makaze** [comment]
You're very welcome! Thank you for checking it

**Pull request merged**
