### PR TITLE
More complex non-alpha test

### PR DESCRIPTION
**Pull request by azh412**
I added a test for a more complex non-alpha test to the check50 tests. This test ensures that the student looks out for all non-alpha characters, and not just commas, or the like.

### CODE REVIEW

**Comment by azh412** [comment]
I made a final change, to enhance the test, thanks!

**Comment by azh412** [comment]
I made a final change by enhancing the test case.

**Comment by azh412** [comment]
Ready for review.

**Comment by brianyu28** [comment]
Thanks for the suggestion! We'll likely keep the checks as-is though, since we already have coverage of other non-alphabetic characters in the `single_sentence_complex` test (checks for commas, quotation marks, and colons, for example).

**Pull request closed without merging**
